
ALTER TABLE public.recipes
  ADD COLUMN IF NOT EXISTS calories INTEGER DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS protein REAL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS carbs REAL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS fat REAL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS fiber REAL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS sugar REAL DEFAULT NULL;
