// Auto-detect grocery category from item name

const categoryKeywords: Record<string, string[]> = {
  Produce: [
    "apple", "banana", "orange", "lemon", "lime", "grape", "berry", "blueberry",
    "strawberry", "raspberry", "blackberry", "cranberry", "mango", "pineapple",
    "peach", "pear", "plum", "cherry", "avocado", "tomato", "potato", "onion",
    "garlic", "ginger", "carrot", "celery", "broccoli", "cauliflower", "spinach",
    "kale", "lettuce", "arugula", "cabbage", "zucchini", "squash", "cucumber",
    "pepper", "bell pepper", "jalapeño", "jalapeno", "habanero", "serrano",
    "poblano", "mushroom", "corn", "peas", "bean sprout", "radish", "beet",
    "turnip", "sweet potato", "asparagus", "artichoke", "eggplant", "aubergine",
    "cilantro", "parsley", "basil", "mint", "dill", "rosemary", "thyme", "sage",
    "chive", "scallion", "green onion", "shallot", "leek", "fennel", "bok choy",
    "watercress", "pomegranate", "fig", "date", "kiwi", "melon", "watermelon",
    "cantaloupe", "coconut", "papaya", "plantain", "lemongrass", "fresh herb",
    "salad", "mixed greens", "spring mix", "romaine", "iceberg", "endive",
    "radicchio", "sprout", "microgreen", "snap pea", "snow pea", "green bean",
    "string bean", "okra", "jicama", "taro", "yam", "rutabaga", "parsnip",
    "celeriac", "collard", "mustard green", "swiss chard", "chard", "dandelion",
    "sorrel", "rhubarb", "starfruit", "dragon fruit", "passion fruit", "lychee",
    "guava", "persimmon", "apricot", "nectarine", "tangerine", "clementine",
    "mandarin", "grapefruit", "blood orange", "kumquat", "jackfruit", "durian",
    "tamarind", "cactus", "nopal", "chayote", "bitter melon", "daikon",
    "horseradish", "turmeric root", "ginger root", "galangal", "Thai basil",
    "oregano fresh", "tarragon", "marjoram", "lavender", "edamame",
    "fresh produce", "fruit", "vegetable", "veggie", "herb",
  ],
  Dairy: [
    "milk", "cream", "butter", "cheese", "yogurt", "yoghurt", "sour cream",
    "cream cheese", "cottage cheese", "ricotta", "mozzarella", "parmesan",
    "cheddar", "feta", "gouda", "brie", "gruyere", "gruyère", "mascarpone",
    "whipping cream", "heavy cream", "half and half", "egg", "eggs", "ghee",
    "queso", "paneer", "halloumi", "havarti", "swiss cheese", "provolone",
    "monterey jack", "colby", "pepper jack", "american cheese", "blue cheese",
    "gorgonzola", "roquefort", "camembert", "burrata", "oat milk", "almond milk",
    "soy milk", "coconut yogurt", "kefir", "buttermilk", "evaporated milk",
    "condensed milk", "whipped cream", "crème fraîche", "creme fraiche",
    "custard", "pudding mix", "eggnog",
  ],
  Meat: [
    "chicken", "beef", "pork", "lamb", "turkey", "duck", "bacon", "sausage",
    "ham", "steak", "ground beef", "ground turkey", "ground pork", "ground lamb",
    "veal", "brisket", "ribs", "wing", "thigh", "breast", "drumstick",
    "tenderloin", "chorizo", "prosciutto", "salami", "pepperoni", "meatball",
    "hot dog", "frankfurter", "bratwurst", "kielbasa", "andouille", "mortadella",
    "pancetta", "guanciale", "jerky", "beef jerky", "deli meat", "lunch meat",
    "roast beef", "corned beef", "pastrami", "meat", "liver", "organ",
    "ground chicken", "pulled pork", "carnitas", "al pastor", "flank",
    "sirloin", "ribeye", "rib eye", "t-bone", "filet mignon", "chuck",
    "round", "rump", "shank", "oxtail", "bone marrow", "bone-in",
    "boneless", "skinless", "cutlet", "chop", "loin", "rack of lamb",
    "leg of lamb", "venison", "bison", "elk", "rabbit", "quail", "goose",
    "pheasant", "cornish hen", "deli", "cold cut",
  ],
  Seafood: [
    "fish", "salmon", "tuna", "shrimp", "prawn", "crab", "lobster", "scallop",
    "mussel", "clam", "oyster", "squid", "calamari", "cod", "halibut", "tilapia",
    "sardine", "anchovy", "mackerel", "trout", "bass", "swordfish", "mahi",
    "octopus", "catfish", "snapper", "grouper", "perch", "walleye", "pike",
    "haddock", "pollock", "sole", "flounder", "sea bass", "branzino", "monkfish",
    "ahi", "yellowtail", "ceviche", "sashimi", "crab meat", "crab cake",
    "fish fillet", "fish stick", "surimi", "imitation crab", "smoked salmon",
    "lox", "caviar", "roe", "uni", "sea urchin", "abalone", "conch",
    "crawfish", "crayfish", "langoustine", "seafood",
  ],
  Bakery: [
    "bread", "baguette", "roll", "bun", "croissant", "tortilla", "pita",
    "naan", "flatbread", "bagel", "english muffin", "sourdough", "ciabatta",
    "brioche", "focaccia", "wrap", "cake", "muffin", "scone", "danish",
    "donut", "doughnut", "pastry", "pie crust", "phyllo", "puff pastry",
    "crumpet", "cornbread", "biscuit", "pretzel", "challah", "rye bread",
    "pumpernickel", "wheat bread", "white bread", "multigrain", "whole wheat",
    "hamburger bun", "hot dog bun", "slider bun", "dinner roll", "kaiser roll",
    "hoagie", "sub roll", "lavash", "matzo", "flour tortilla", "corn tortilla",
    "taco shell",
  ],
  Pantry: [
    "flour", "sugar", "salt", "pepper", "oil", "olive oil", "vegetable oil",
    "canola oil", "sesame oil", "avocado oil", "grapeseed oil", "coconut oil",
    "vinegar", "balsamic", "apple cider vinegar", "rice vinegar", "white vinegar",
    "red wine vinegar", "soy sauce", "tamari", "fish sauce", "oyster sauce",
    "hoisin", "teriyaki", "worcestershire", "hot sauce", "sriracha", "tabasco",
    "ketchup", "mustard", "dijon", "mayo", "mayonnaise", "honey", "agave",
    "maple syrup", "molasses", "vanilla", "extract", "almond extract",
    "baking soda", "baking powder", "yeast", "cornstarch", "arrowroot",
    "cocoa", "cocoa powder", "chocolate", "chocolate chip", "chips",
    "nuts", "almond", "walnut", "pecan", "cashew", "peanut", "pistachio",
    "macadamia", "hazelnut", "brazil nut", "pine nut", "mixed nuts",
    "sesame", "sunflower seed", "pumpkin seed", "chia", "flax", "hemp seed",
    "poppy seed",
    "oat", "oats", "oatmeal", "rice", "basmati", "jasmine rice", "brown rice",
    "wild rice", "arborio", "sushi rice", "pasta", "noodle", "spaghetti",
    "penne", "macaroni", "fusilli", "rigatoni", "linguine", "fettuccine",
    "lasagna", "orzo", "ramen", "udon", "soba", "rice noodle", "vermicelli",
    "egg noodle", "couscous", "quinoa", "bulgur", "farro", "barley", "millet",
    "polenta", "cornmeal", "grits",
    "lentil", "chickpea", "black bean", "kidney bean", "pinto bean", "navy bean",
    "white bean", "cannellini", "great northern", "lima bean", "split pea",
    "canned", "broth", "stock", "bouillon", "tomato paste", "tomato sauce",
    "diced tomato", "crushed tomato", "san marzano", "marinara",
    "coconut milk", "coconut cream", "peanut butter", "almond butter",
    "tahini", "nutella", "jam", "jelly", "preserve", "marmalade",
    "cereal", "granola", "muesli", "cracker", "breadcrumb", "panko",
    "spice", "cumin", "paprika", "smoked paprika", "turmeric", "cinnamon",
    "nutmeg", "oregano", "chili powder", "chili flake", "curry", "curry powder",
    "curry paste", "garam masala", "coriander", "cardamom", "clove", "allspice",
    "star anise", "bay leaf", "red pepper flake", "cayenne", "black pepper",
    "white pepper", "garlic powder", "onion powder", "Italian seasoning",
    "everything bagel seasoning", "taco seasoning", "ranch seasoning",
    "old bay", "five spice", "za'atar", "sumac", "saffron", "fennel seed",
    "celery seed", "mustard seed", "dill seed", "caraway",
    "dried", "dried fruit", "raisin", "craisin", "dried cranberry",
    "dried apricot", "prune", "dried mango",
    "tortilla chip", "potato chip", "popcorn", "pretzel stick",
    "salsa", "guacamole", "hummus", "pesto", "bbq sauce", "steak sauce",
    "relish", "capers", "olive", "pickle", "pickled", "kimchi", "sauerkraut",
    "miso", "miso paste", "gochujang", "sambal", "chutney",
    "gelatin", "agar", "cornmeal", "masa", "tapioca",
    "powdered sugar", "brown sugar", "turbinado", "stevia", "splenda",
    "protein powder", "collagen", "nutritional yeast",
  ],
  Frozen: [
    "frozen", "ice cream", "gelato", "sorbet", "popsicle", "frozen pizza",
    "frozen vegetable", "frozen fruit", "frozen dinner", "frozen meal",
    "frozen fries", "frozen burger", "frozen chicken", "frozen fish",
    "ice", "frozen waffle", "frozen bread", "frozen pie",
  ],
  Beverages: [
    "water", "juice", "soda", "pop", "coffee", "tea", "wine", "beer", "cider",
    "sparkling", "seltzer", "tonic", "club soda", "kombucha", "lemonade",
    "smoothie", "energy drink", "sports drink", "gatorade", "coconut water",
    "almond milk", "oat milk", "chai", "matcha", "espresso", "cold brew",
    "iced tea", "iced coffee", "hot chocolate", "cocoa mix",
    "whiskey", "vodka", "rum", "gin", "tequila", "brandy", "bourbon",
    "champagne", "prosecco", "sake", "mead",
  ],
  "Condiments & Sauces": [
    "dressing", "salad dressing", "ranch", "vinaigrette", "caesar dressing",
    "blue cheese dressing", "italian dressing", "thousand island",
    "barbecue sauce", "buffalo sauce", "wing sauce", "cocktail sauce",
    "tartar sauce", "aioli", "remoulade", "chimichurri", "sofrito",
    "enchilada sauce", "mole", "adobo", "harissa", "tahini sauce",
    "ponzu", "sweet chili sauce", "plum sauce", "duck sauce",
    "cream sauce", "alfredo", "bolognese", "ragu", "gravy",
    "maple butter", "compound butter",
  ],
};

export const allCategories = [
  "Produce",
  "Dairy",
  "Meat",
  "Seafood",
  "Bakery",
  "Pantry",
  "Condiments & Sauces",
  "Frozen",
  "Beverages",
  "Other",
];

export function detectCategory(itemName: string): string {
  const lower = itemName.toLowerCase().trim();

  for (const [category, keywords] of Object.entries(categoryKeywords)) {
    for (const keyword of keywords) {
      if (lower === keyword || lower.includes(keyword)) {
        return category;
      }
    }
  }

  return "Other";
}
